local objectname = "arkanium"
local featureDef = {
	name			= "arkanium",
	world			= "All Worlds",
	description		= "A rare and valuable mineral",
	category		= "Vegetation",
	object			= "arkanium.s3o",
	footprintx		= 2,
	footprintz		= 2,
	height			=30,
	blocking		=true,
	upright			=true,
	hitdensity		= 0,
	energy			= 0,
	metal			= 100,
	damage			= 50,
	flammable		= false,
	reclaimable		= true,
	autoreclaimable	=true,
}
return lowerkeys({[objectname] = featureDef})