local objectname= "brock_1" 
local featureDef	=	{
	name			= "brock_1",
	world				="All Worlds",
	description				="Rock",
	category				="Vegetation",
	object				="arkanium.s3o",
	footprintx				=1,
	footprintz				=1,
	height				=30,
	blocking				=true,
	upright				=false,
	hitdensity				=1,
	energy				=0,
	metal				=20,
	damage				=3000,
	flammable				=false,
	reclaimable				=true,
	autoreclaimable				=true,
} 
return lowerkeys({[objectname] = featureDef}) 
